-- Run this in Supabase SQL editor.
-- Profile backend + RLS for:
-- 1) profile name ownership
-- 2) posted items (items you list)
-- 3) received items (items you won/received)

begin;

alter table public.profiles enable row level security;
alter table public.items enable row level security;

-- Keep profile defaults stable for insert/upsert flows.
alter table public.profiles
  alter column wins set default 0,
  alter column "totalBets" set default 0;

update public.profiles
set
  name = coalesce(nullif(trim(name), ''), 'Player ' || left(id::text, 8)),
  wins = coalesce(wins, 0),
  "totalBets" = coalesce("totalBets", 0)
where name is null
  or trim(name) = ''
  or wins is null
  or "totalBets" is null;

drop policy if exists "profiles_select_own" on public.profiles;
drop policy if exists "profiles_insert_own" on public.profiles;
drop policy if exists "profiles_update_own" on public.profiles;

create policy "profiles_select_own"
on public.profiles
for select
to authenticated
using (auth.uid() = id);

create policy "profiles_insert_own"
on public.profiles
for insert
to authenticated
with check (auth.uid() = id);

create policy "profiles_update_own"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "items_select_authenticated" on public.items;
drop policy if exists "items_insert_own" on public.items;
drop policy if exists "items_update_own" on public.items;
drop policy if exists "items_delete_own" on public.items;

create policy "items_select_authenticated"
on public.items
for select
to authenticated
using (true);

create policy "items_insert_own"
on public.items
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "items_update_own"
on public.items
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "items_delete_own"
on public.items
for delete
to authenticated
using (auth.uid() = user_id);

create table if not exists public.profile_received_items (
  received_id bigint generated by default as identity primary key,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  item_id text not null,
  sender_id uuid references public.profiles(id) on delete set null,
  note text,
  received_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  unique (receiver_id, item_id)
);

create index if not exists profile_received_items_receiver_idx
  on public.profile_received_items (receiver_id, received_at desc);

create index if not exists profile_received_items_item_idx
  on public.profile_received_items (item_id);

alter table public.profile_received_items enable row level security;

drop policy if exists "profile_received_items_select_own" on public.profile_received_items;
drop policy if exists "profile_received_items_insert_own" on public.profile_received_items;
drop policy if exists "profile_received_items_delete_own" on public.profile_received_items;

create policy "profile_received_items_select_own"
on public.profile_received_items
for select
to authenticated
using (auth.uid() = receiver_id);

create policy "profile_received_items_insert_own"
on public.profile_received_items
for insert
to authenticated
with check (auth.uid() = receiver_id);

create policy "profile_received_items_delete_own"
on public.profile_received_items
for delete
to authenticated
using (auth.uid() = receiver_id);

create or replace function public.set_my_profile_name(input_name text)
returns public.profiles
language plpgsql
security invoker
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  cleaned_name text;
  updated_profile public.profiles;
begin
  if current_user_id is null then
    raise exception using
      message = 'You must be signed in to update your profile name.',
      errcode = '42501';
  end if;

  cleaned_name := left(
    regexp_replace(coalesce(trim(input_name), ''), '[^a-zA-Z0-9 _.-]', '', 'g'),
    64
  );

  if char_length(cleaned_name) < 3 then
    raise exception using
      message = 'Name must be at least 3 characters after cleanup.',
      errcode = '22023';
  end if;

  insert into public.profiles (id, name, wins, "totalBets")
  values (current_user_id, cleaned_name, 0, 0)
  on conflict (id)
  do update
    set name = excluded.name
  returning * into updated_profile;

  return updated_profile;
end;
$$;

create or replace function public.post_my_item(
  item_name text,
  item_desc text,
  item_price numeric,
  item_url text,
  item_category text default null,
  item_condition text default 'Good'
)
returns public.items
language plpgsql
security invoker
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  normalized_condition text;
  inserted_item public.items;
begin
  if current_user_id is null then
    raise exception using
      message = 'You must be signed in to post an item.',
      errcode = '42501';
  end if;

  if nullif(trim(item_name), '') is null then
    raise exception using message = 'Item name is required.', errcode = '22023';
  end if;

  if item_price is null or item_price <= 0 then
    raise exception using message = 'Item price must be greater than 0.', errcode = '22023';
  end if;

  normalized_condition := case
    when item_condition in ('New', 'Like New', 'Good', 'Fair') then item_condition
    else 'Good'
  end;

  insert into public.items (name, "desc", price, url, category, condition, user_id)
  values (
    trim(item_name),
    coalesce(trim(item_desc), ''),
    item_price,
    coalesce(nullif(trim(item_url), ''), '/file.svg'),
    coalesce(nullif(trim(item_category), ''), 'Misc'),
    normalized_condition,
    current_user_id
  )
  returning * into inserted_item;

  return inserted_item;
end;
$$;

create or replace function public.add_received_item(
  received_item_id text,
  from_profile_id uuid default null,
  received_note text default null
)
returns public.profile_received_items
language plpgsql
security invoker
set search_path = public
as $$
declare
  current_user_id uuid := auth.uid();
  normalized_item_id text;
  receipt_row public.profile_received_items;
begin
  if current_user_id is null then
    raise exception using
      message = 'You must be signed in to add a received item.',
      errcode = '42501';
  end if;

  normalized_item_id := nullif(trim(received_item_id), '');
  if normalized_item_id is null then
    raise exception using message = 'received_item_id is required.', errcode = '22023';
  end if;

  if not exists (
    select 1
    from public.items i
    where i.item_id::text = normalized_item_id
  ) then
    raise exception using
      message = 'Item does not exist.',
      errcode = '23503';
  end if;

  insert into public.profile_received_items (receiver_id, item_id, sender_id, note)
  values (
    current_user_id,
    normalized_item_id,
    from_profile_id,
    nullif(trim(received_note), '')
  )
  on conflict (receiver_id, item_id)
  do update
    set sender_id = excluded.sender_id,
        note = coalesce(excluded.note, public.profile_received_items.note),
        received_at = timezone('utc', now())
  returning * into receipt_row;

  return receipt_row;
end;
$$;

create or replace function public.get_my_profile_backend()
returns jsonb
language sql
security invoker
set search_path = public
as $$
with me as (
  select p.id, p.avatar_url, p.name, p.wins, p."totalBets"
  from public.profiles p
  where p.id = auth.uid()
)
select coalesce(
  (
    select jsonb_build_object(
      'profile',
      jsonb_build_object(
        'id', me.id,
        'avatar_url', me.avatar_url,
        'name', me.name,
        'wins', me.wins,
        'totalBets', me."totalBets"
      ),
      'postedItems',
      coalesce(
        (
          select jsonb_agg(
            jsonb_build_object(
              'item_id', i.item_id,
              'name', i.name,
              'desc', i."desc",
              'price', i.price,
              'url', i.url,
              'category', i.category,
              'condition', i.condition,
              'user_id', i.user_id
            )
            order by i.item_id desc
          )
          from public.items i
          where i.user_id = me.id
        ),
        '[]'::jsonb
      ),
      'receivedItems',
      coalesce(
        (
          select jsonb_agg(
            jsonb_build_object(
              'received_id', r.received_id,
              'received_at', r.received_at,
              'note', r.note,
              'sender_id', r.sender_id,
              'sender_name', sender.name,
              'item',
              jsonb_build_object(
                'item_id', coalesce(i.item_id::text, r.item_id),
                'name', coalesce(i.name, 'Unknown Item'),
                'desc', coalesce(i."desc", ''),
                'price', coalesce(i.price, 0),
                'url', coalesce(i.url, ''),
                'category', coalesce(i.category, 'Misc'),
                'condition', coalesce(i.condition, 'Good'),
                'user_id', i.user_id
              )
            )
            order by r.received_at desc
          )
          from public.profile_received_items r
          left join public.items i
            on i.item_id::text = r.item_id
          left join public.profiles sender
            on sender.id = r.sender_id
          where r.receiver_id = me.id
        ),
        '[]'::jsonb
      )
    )
    from me
  ),
  jsonb_build_object(
    'profile', null,
    'postedItems', '[]'::jsonb,
    'receivedItems', '[]'::jsonb
  )
);
$$;

create or replace function public.get_profile_names(profile_ids uuid[])
returns table (id uuid, name text)
language sql
security definer
set search_path = public
as $$
  select p.id, coalesce(nullif(trim(p.name), ''), 'Player') as name
  from public.profiles p
  where p.id = any(profile_ids);
$$;

grant execute on function public.set_my_profile_name(text) to authenticated;
grant execute on function public.post_my_item(text, text, numeric, text, text, text) to authenticated;
grant execute on function public.add_received_item(text, uuid, text) to authenticated;
grant execute on function public.get_my_profile_backend() to authenticated;
grant execute on function public.get_profile_names(uuid[]) to authenticated;

commit;
