-- Run this in Supabase SQL editor after profiles-rls.sql.

begin;

create table if not exists public.trade_requests (
  trade_id bigint generated by default as identity primary key,
  requester_id uuid not null references public.profiles(id) on delete cascade,
  recipient_id uuid not null references public.profiles(id) on delete cascade,
  requester_item_id bigint not null references public.items(item_id) on delete cascade,
  recipient_item_id bigint not null references public.items(item_id) on delete cascade,
  requester_approved boolean not null default true,
  recipient_approved boolean not null default false,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'declined', 'cancelled', 'completed')),
  meetup_location text not null default 'Central PD',
  declined_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  check (requester_id <> recipient_id),
  check (requester_item_id <> recipient_item_id)
);

create index if not exists trade_requests_requester_idx
  on public.trade_requests (requester_id, created_at desc);

create index if not exists trade_requests_recipient_idx
  on public.trade_requests (recipient_id, created_at desc);

create index if not exists trade_requests_status_idx
  on public.trade_requests (status, created_at desc);

create or replace function public.set_trade_request_updated_at()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists trade_requests_set_updated_at on public.trade_requests;

create trigger trade_requests_set_updated_at
before update on public.trade_requests
for each row
execute procedure public.set_trade_request_updated_at();

alter table public.trade_requests enable row level security;

drop policy if exists "trade_requests_select_participants" on public.trade_requests;
drop policy if exists "trade_requests_insert_requester" on public.trade_requests;
drop policy if exists "trade_requests_update_participants" on public.trade_requests;

create policy "trade_requests_select_participants"
on public.trade_requests
for select
to authenticated
using (auth.uid() = requester_id or auth.uid() = recipient_id);

create policy "trade_requests_insert_requester"
on public.trade_requests
for insert
to authenticated
with check (auth.uid() = requester_id);

create policy "trade_requests_update_participants"
on public.trade_requests
for update
to authenticated
using (auth.uid() = requester_id or auth.uid() = recipient_id)
with check (auth.uid() = requester_id or auth.uid() = recipient_id);

commit;
